$component({
  props:{value:{},open:{},disabled:{},readonly:{},format:{},onValueChange:{},onOpenChange:{}},
  init:({els,data,props,effect,i18n})=>{
    const root=els[0],native=root?.querySelector(':scope > [data-citry-ui-part="native"]'),trigger=root?.querySelector(':scope > [data-citry-ui-part="trigger"]'),preview=trigger?.querySelector('[data-citry-ui-part="preview"]'),valueText=trigger?.querySelector('[data-citry-ui-part="value"]'),popup=root?.querySelector(':scope > [data-citry-ui-part="popup"]'),area=popup?.querySelector('[data-citry-color-picker-area]'),thumb=area?.querySelector('[data-citry-ui-part="area-thumb"]'),hue=popup?.querySelector('[data-citry-ui-part="hue"] input'),formatSelect=popup?.querySelector('[data-citry-ui-part="format"]'),input=popup?.querySelector('[data-citry-ui-part="input"]'),status=root?.querySelector(':scope > [data-citry-ui-part="status"]');
    if(!(root instanceof HTMLElement)||!(native instanceof HTMLInputElement)||!(trigger instanceof HTMLButtonElement)||!preview||!valueText||!(popup instanceof HTMLElement)||!(area instanceof HTMLElement)||!thumb||!(hue instanceof HTMLInputElement)||!(formatSelect instanceof HTMLSelectElement)||!(input instanceof HTMLInputElement)||!status)throw new Error('[citry-ui] CColorPicker settled anatomy is invalid.');
    const swatches=[...popup.querySelectorAll('[data-citry-color-swatch]')],invalid=new Set();
    let accepted=data.value,current=accepted,currentOpen=data.open,disabled=data.disabled,readonly=data.readonly,format=data.format,valueControlled=false,openControlled=false,valueCallback=null,openCallback=null,outside=false,dragging=false,internal=false;
    const report=(name,value)=>{if(invalid.has(name))return;invalid.add(name);console.error(`[citry-ui] CColorPicker ${name} received invalid client value.`,value,root);};
    const clamp=(value,min,max)=>Math.min(max,Math.max(min,value)),hex=value=>typeof value==='string'&&/^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(value)?(value.length===4?'#'+[...value.slice(1)].map(x=>x+x).join(''):value).toLowerCase():null;
    const hexRgb=value=>({r:parseInt(value.slice(1,3),16),g:parseInt(value.slice(3,5),16),b:parseInt(value.slice(5,7),16)}),rgbHex=({r,g,b})=>'#'+[r,g,b].map(value=>Math.round(clamp(value,0,255)).toString(16).padStart(2,'0')).join('');
    const rgbHsv=({r,g,b})=>{r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d)h=max===r?60*(((g-b)/d)%6):max===g?60*((b-r)/d+2):60*((r-g)/d+4);if(h<0)h+=360;return{h,s:max?d/max*100:0,v:max*100};};
    const hsvRgb=({h,s,v})=>{s/=100;v/=100;const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let parts=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return{r:(parts[0]+m)*255,g:(parts[1]+m)*255,b:(parts[2]+m)*255};};
    const rgbHsl=rgb=>{const hsv=rgbHsv(rgb),r=rgb.r/255,g=rgb.g/255,b=rgb.b/255,max=Math.max(r,g,b),min=Math.min(r,g,b),l=(max+min)/2,d=max-min,s=d===0?0:d/(1-Math.abs(2*l-1));return{h:hsv.h,s:s*100,l:l*100};};
    const hslRgb=({h,s,l})=>{s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let parts=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return{r:(parts[0]+m)*255,g:(parts[1]+m)*255,b:(parts[2]+m)*255};};
    const display=value=>{const rgb=hexRgb(value);if(format==='rgb')return`${rgb.r}, ${rgb.g}, ${rgb.b}`;if(format==='hsl'){const hsl=rgbHsl(rgb);return`${Math.round(hsl.h)}, ${Math.round(hsl.s)}%, ${Math.round(hsl.l)}%`;}return value;};
    const parseText=text=>{if(format==='hex')return hex(text.trim());const values=text.replace(/^(rgb|hsl)a?\(/i,'').replace(/\)$/,'').split(/[\s,\/]+/).filter(Boolean).map(value=>Number(value.replace('%','')));if(values.length!==3||values.some(value=>!Number.isFinite(value)))return null;if(format==='rgb'&&values.every(value=>value>=0&&value<=255))return rgbHex({r:values[0],g:values[1],b:values[2]});if(format==='hsl'&&values[0]>=0&&values[0]<=360&&values[1]>=0&&values[1]<=100&&values[2]>=0&&values[2]<=100)return rgbHex(hslRgb({h:values[0]%360,s:values[1],l:values[2]}));return null;};
    const message=(kind,color)=>{if(i18n&&data.catalog[kind])try{return i18n.tr(`citry-ui-color-picker-${kind}`,kind==='selected'?{color}:undefined);}catch(error){console.error('[citry-ui] CColorPicker translation failed.',error,root);}return kind==='selected'?data.labels.selected.replaceAll('{color}',color):data.labels[kind];};
    const sync=()=>{const hsv=rgbHsv(hexRgb(current));native.value=current;preview.style.backgroundColor=current;valueText.textContent=current;area.style.setProperty('--_cui-color-picker-hue',`hsl(${hsv.h} 100% 50%)`);area.style.setProperty('--_cui-color-picker-saturation',`${hsv.s}%`);area.style.setProperty('--_cui-color-picker-brightness',`${100-hsv.v}%`);area.setAttribute('aria-valuenow',String(Math.round(hsv.v)));area.setAttribute('aria-valuetext',`${Math.round(hsv.s)}% saturation, ${Math.round(hsv.v)}% brightness, ${current}`);area.setAttribute('aria-disabled',String(disabled));area.setAttribute('aria-readonly',String(readonly));thumb.style.insetInlineStart=`${hsv.s}%`;thumb.style.insetBlockStart=`${100-hsv.v}%`;hue.value=String(Math.round(hsv.h)%360);hue.disabled=disabled||readonly;formatSelect.value=format;formatSelect.disabled=disabled;input.disabled=disabled;input.readOnly=readonly;input.value=display(current);trigger.disabled=disabled;trigger.setAttribute('aria-expanded',String(currentOpen));popup.hidden=!currentOpen;root.toggleAttribute('data-open',currentOpen);root.toggleAttribute('data-disabled',disabled);root.toggleAttribute('data-readonly',readonly);root.dataset.format=format;for(const swatch of swatches){const selected=swatch.dataset.value===current;swatch.setAttribute('aria-pressed',String(selected));swatch.toggleAttribute('data-selected',selected);swatch.disabled=disabled||readonly;}if(currentOpen&&!outside){document.addEventListener('pointerdown',onOutside,true);outside=true;}else if(!currentOpen&&outside){document.removeEventListener('pointerdown',onOutside,true);outside=false;}};
    const detail=(next,previous,source,event)=>({value:next,previousValue:previous,rgb:hexRgb(next),hsl:rgbHsl(hexRgb(next)),hsv:rgbHsv(hexRgb(next)),controlled:valueControlled,source,sourceEvent:event});
    const requestValue=(next,source,event,announce=true)=>{next=hex(next);if(!next||next===current)return;const previous=current;try{valueCallback?.(next,detail(next,previous,source,event));}catch(error){console.error('[citry-ui] CColorPicker onValueChange callback failed.',error,root);}if(!valueControlled){accepted=next;current=next;internal=true;native.value=next;native.dispatchEvent(new Event('input',{bubbles:true}));native.dispatchEvent(new Event('change',{bubbles:true}));internal=false;if(announce)status.textContent=message('selected',next);}sync();};
    function requestOpen(next,reason,event){if(disabled||next===currentOpen)return;try{openCallback?.(next,{open:next,reason,sourceEvent:event});}catch(error){console.error('[citry-ui] CColorPicker onOpenChange callback failed.',error,root);}if(!openControlled){currentOpen=next;sync();}if(!next&&['escape','selection'].includes(reason))trigger.focus();}
    const fromArea=event=>{if(disabled||readonly)return;const rect=area.getBoundingClientRect(),hsv=rgbHsv(hexRgb(current));requestValue(rgbHex(hsvRgb({h:hsv.h,s:clamp((event.clientX-rect.left)/rect.width*100,0,100),v:clamp((rect.bottom-event.clientY)/rect.height*100,0,100)})),'area',event,false);};
    const onAreaDown=event=>{if(disabled||readonly)return;dragging=true;area.setPointerCapture(event.pointerId);fromArea(event);};const onAreaMove=event=>{if(dragging)fromArea(event);};const onAreaUp=event=>{if(!dragging)return;dragging=false;area.releasePointerCapture(event.pointerId);status.textContent=message('selected',current);};
    const onAreaKey=event=>{if(disabled||readonly)return;const hsv=rgbHsv(hexRgb(current));let next={...hsv};if(event.key==='ArrowLeft')next.s-=1;else if(event.key==='ArrowRight')next.s+=1;else if(event.key==='ArrowUp')next.v+=1;else if(event.key==='ArrowDown')next.v-=1;else if(event.key==='Home')next.s=0;else if(event.key==='End')next.s=100;else if(event.key==='PageUp')next.v+=10;else if(event.key==='PageDown')next.v-=10;else return;event.preventDefault();next.s=clamp(next.s,0,100);next.v=clamp(next.v,0,100);requestValue(rgbHex(hsvRgb(next)),'area',event);};
    const commitText=event=>{const next=parseText(input.value);if(!next){input.setAttribute('aria-invalid','true');status.textContent=message('invalid');return;}input.removeAttribute('aria-invalid');requestValue(next,'text',event);input.value=display(current);};
    const onOutside=event=>{if(!root.contains(event.target))requestOpen(false,'outside',event);};const onTrigger=event=>requestOpen(!currentOpen,'trigger',event);const onHue=event=>{if(disabled||readonly)return;const hsv=rgbHsv(hexRgb(current));requestValue(rgbHex(hsvRgb({h:Number(hue.value),s:hsv.s,v:hsv.v})),'hue',event,false);};
    const onFormat=()=>{format=formatSelect.value;root.dataset.format=format;input.removeAttribute('aria-invalid');input.value=display(current);};const onInputKey=event=>{if(event.key==='Enter'){event.preventDefault();commitText(event);}else if(event.key==='Escape'){input.removeAttribute('aria-invalid');input.value=display(current);}};const onSwatch=event=>{const swatch=event.target.closest('[data-citry-color-swatch]');if(swatch)requestValue(swatch.dataset.value,'swatch',event);};const onNative=event=>{if(!internal)requestValue(native.value,'native',event);};const onPopupKey=event=>{if(event.key==='Escape'){event.preventDefault();requestOpen(false,'escape',event);}};
    const onReset=event=>{if(event.target!==native.form)return;setTimeout(()=>{const next=native.defaultValue;if(valueControlled)valueCallback?.(next,detail(next,current,'reset',event));else{accepted=next;current=next;sync();}},0);};
    trigger.addEventListener('click',onTrigger);area.addEventListener('pointerdown',onAreaDown);area.addEventListener('pointermove',onAreaMove);area.addEventListener('pointerup',onAreaUp);area.addEventListener('pointercancel',onAreaUp);area.addEventListener('keydown',onAreaKey);hue.addEventListener('input',onHue);hue.addEventListener('change',event=>status.textContent=message('selected',current));formatSelect.addEventListener('change',onFormat);input.addEventListener('keydown',onInputKey);input.addEventListener('change',commitText);popup.addEventListener('click',onSwatch);popup.addEventListener('keydown',onPopupKey);native.addEventListener('input',onNative);native.form?.addEventListener('reset',onReset);native.hidden=true;trigger.hidden=false;root.setAttribute('data-citry-color-picker-initialized','');
    effect(()=>{const nextValue=props.value;valueControlled=nextValue!=null;if(valueControlled){const valid=hex(nextValue);if(valid){invalid.delete('value');current=valid;}else{report('value',nextValue);current=accepted;}}else{invalid.delete('value');current=accepted;}for(const name of ['disabled','readonly']){const supplied=props[name];if(supplied!==undefined&&typeof supplied!=='boolean')report(name,supplied);else{invalid.delete(name);if(name==='disabled')disabled=typeof supplied==='boolean'?supplied:data.disabled;else readonly=typeof supplied==='boolean'?supplied:data.readonly;}}const nextFormat=props.format;if(nextFormat!==undefined&&!['hex','rgb','hsl'].includes(nextFormat))report('format',nextFormat);else{invalid.delete('format');format=nextFormat??data.format;}const nextOpen=props.open;openControlled=nextOpen!=null;if(openControlled&&typeof nextOpen!=='boolean'){report('open',nextOpen);currentOpen=data.open;}else{invalid.delete('open');if(openControlled)currentOpen=nextOpen;}for(const [name,setter] of [['onValueChange',value=>valueCallback=value],['onOpenChange',value=>openCallback=value]]){const supplied=props[name];if(supplied==null){setter(null);invalid.delete(name);}else if(typeof supplied==='function'){setter(supplied);invalid.delete(name);}else report(name,supplied);}sync();});
    return()=>{dragging=false;if(outside)document.removeEventListener('pointerdown',onOutside,true);native.form?.removeEventListener('reset',onReset);trigger.removeEventListener('click',onTrigger);area.removeEventListener('pointerdown',onAreaDown);area.removeEventListener('pointermove',onAreaMove);area.removeEventListener('pointerup',onAreaUp);area.removeEventListener('pointercancel',onAreaUp);area.removeEventListener('keydown',onAreaKey);hue.removeEventListener('input',onHue);formatSelect.removeEventListener('change',onFormat);input.removeEventListener('keydown',onInputKey);input.removeEventListener('change',commitText);popup.removeEventListener('click',onSwatch);popup.removeEventListener('keydown',onPopupKey);native.removeEventListener('input',onNative);native.hidden=false;trigger.hidden=true;root.removeAttribute('data-citry-color-picker-initialized');};
  }
});
