"""First-party styled and headless components for Citry."""

from importlib.metadata import PackageNotFoundError, version

from citry import ComponentLibrary
from citry_ui.components import (
    COMPONENTS,
    CButton,
    CButtonDefaultSlotData,
    CButtonHeadless,
    CButtonHeadlessDefaultSlotData,
    CButtonType,
    CField,
    CFieldDefaultSlotData,
    CFieldDensity,
    CFieldDescriptionSlotData,
    CFieldErrorSlotData,
    CFieldHeadless,
    CFieldHeadlessDefaultSlotData,
    CFieldLabelSlotData,
    CFieldOrientation,
    CInput,
    CInputHeadless,
    CInputHeadlessDefaultSlotData,
    CInputType,
    CTab,
    CTabDefaultSlotData,
    CTabHeadless,
    CTabHeadlessDefaultSlotData,
    CTable,
    CTableCaptionSlotData,
    CTableCell,
    CTableCellSlotData,
    CTableColumn,
    CTableDensity,
    CTableEmptySlotData,
    CTableErrorSlotData,
    CTableHeaderSlotData,
    CTableHeadless,
    CTableHeadlessDefaultSlotData,
    CTableLoadingSlotData,
    CTableResolvedCell,
    CTableResolvedColumn,
    CTableResolvedRow,
    CTableRow,
    CTableState,
    CTabList,
    CTabListDefaultSlotData,
    CTabListHeadless,
    CTabListHeadlessDefaultSlotData,
    CTabPanel,
    CTabPanelDefaultSlotData,
    CTabPanelHeadless,
    CTabPanelHeadlessDefaultSlotData,
    CTabs,
    CTabsActivation,
    CTabsDefaultSlotData,
    CTabsDirection,
    CTabsHeadless,
    CTabsHeadlessDefaultSlotData,
    CTabsOrientation,
)

__citry_library__ = ComponentLibrary(
    name="citry-ui",
    components=COMPONENTS,
)

try:
    __version__ = version("citry-ui")
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"

__all__ = [
    "CButton",
    "CButtonDefaultSlotData",
    "CButtonHeadless",
    "CButtonHeadlessDefaultSlotData",
    "CButtonType",
    "CField",
    "CFieldDefaultSlotData",
    "CFieldDensity",
    "CFieldDescriptionSlotData",
    "CFieldErrorSlotData",
    "CFieldHeadless",
    "CFieldHeadlessDefaultSlotData",
    "CFieldLabelSlotData",
    "CFieldOrientation",
    "CInput",
    "CInputHeadless",
    "CInputHeadlessDefaultSlotData",
    "CInputType",
    "CTab",
    "CTabDefaultSlotData",
    "CTabHeadless",
    "CTabHeadlessDefaultSlotData",
    "CTabList",
    "CTabListDefaultSlotData",
    "CTabListHeadless",
    "CTabListHeadlessDefaultSlotData",
    "CTabPanel",
    "CTabPanelDefaultSlotData",
    "CTabPanelHeadless",
    "CTabPanelHeadlessDefaultSlotData",
    "CTable",
    "CTableCaptionSlotData",
    "CTableCell",
    "CTableCellSlotData",
    "CTableColumn",
    "CTableDensity",
    "CTableEmptySlotData",
    "CTableErrorSlotData",
    "CTableHeaderSlotData",
    "CTableHeadless",
    "CTableHeadlessDefaultSlotData",
    "CTableLoadingSlotData",
    "CTableResolvedCell",
    "CTableResolvedColumn",
    "CTableResolvedRow",
    "CTableRow",
    "CTableState",
    "CTabs",
    "CTabsActivation",
    "CTabsDefaultSlotData",
    "CTabsDirection",
    "CTabsHeadless",
    "CTabsHeadlessDefaultSlotData",
    "CTabsOrientation",
    "__citry_library__",
    "__version__",
]
