# citry - Fast, simple, and smart frontend framework for Python
#
# This package provides the rendering runtime for Citry templates:
# component lifecycle, slots, rendering pipeline, and the node classes
# that the V3 compiler output instantiates.
#
# For the Rust-powered parser and compiler, see citry_core.
#
# API stability: the names exported HERE (listed in __all__) are the public
# API, and only these are promised not to break between releases. Submodules
# (citry.slots, citry.nodes, ...) may be imported from, but their contents
# are internal and free to change between releases.

from markupsafe import Markup

from citry._linting import TemplateLintInfo, TemplateVariableInfo
from citry.analysis import (
    LspPosition,
    LspRange,
    PythonComponentAssetDiscovery,
    PythonComponentAssetFile,
    PythonComponentAssetFormatResult,
    PythonComponentAssetKind,
    PythonComponentAssetNotice,
    PythonComponentAssetPlan,
    PythonComponentAssetRegion,
    PythonComponentAssetRequest,
    PythonTemplateDiscovery,
    PythonTemplateFormatError,
    PythonTemplateFormatResult,
    PythonTemplateNotice,
    PythonTemplateRegion,
    PythonTemplateSourceMap,
    TemplateAnalysis,
    TemplateLintConsumer,
    TemplateLintFinding,
    discover_python_component_assets,
    discover_python_templates,
    finish_python_component_assets,
    format_python_component_assets,
    format_python_templates,
    lint_unknown_template_variables,
    prepare_python_component_assets,
)
from citry.attrs import (
    format_attrs,
    merge_attrs,
    normalize_class,
    normalize_style,
    parse_string_style,
)
from citry.cache import CitryCache, InMemoryCache
from citry.citry import (
    Citry,
    citry,
)
from citry.citry_context import CitryContext
from citry.citry_element import CitryElement
from citry.citry_render import (
    CitryRender,
    DepsPosition,
    DepsStrategy,
    OnRenderGenerator,
    Placeholder,
    RenderFrame,
    RenderReplacement,
    SerializedRender,
    SerializedScriptSecurity,
    SerializedSecurity,
)
from citry.citry_template import CitryTemplate
from citry.command import CommandArg, CommandArgGroup, CommandSubcommand
from citry.component import Component
from citry.component_like import ComponentLike
from citry.component_registry import AlreadyRegistered, NotRegistered
from citry.constness import Const, const_value, is_const
from citry.ext.cache import CacheConfig
from citry.ext.dependencies import DependenciesConfig
from citry.ext.events.config import Events
from citry.ext.i18n import (
    CurrencyFormat,
    DateFormat,
    DateFormatFields,
    DateInput,
    DateParseResult,
    DateSegments,
    DateTimeFormat,
    DateTimeInput,
    DateTimeParseResult,
    DateTimeSegments,
    FormatRegistry,
    I18n,
    I18nError,
    I18nFormatter,
    I18nNotConfiguredError,
    I18nParser,
    I18nRuntimeUnavailableError,
    I18nService,
    ListFormat,
    LocaleContext,
    LocalizedText,
    NumberFormat,
    NumberInput,
    NumberParseResult,
    PercentFormat,
    PercentInput,
    PercentParseResult,
    RelativeTimeFormat,
    TimeFormat,
    TimeInput,
    TimeParseResult,
    TimeSegments,
    UnitFormat,
)
from citry.extension import (
    ComponentIntrospectionContext,
    Extension,
    ExtensionCommand,
    ExtensionConfig,
    ExtensionManager,
    NestedClassDeclaration,
    OnAttrsResolvedContext,
    OnCitryClearedContext,
    OnComponentClassCreatedContext,
    OnComponentDataContext,
    OnComponentInputContext,
    OnComponentRegisteredContext,
    OnComponentRenderedContext,
    OnComponentUnregisteredContext,
    OnCssLoadedContext,
    OnExtensionCreatedContext,
    OnFilesResetContext,
    OnJsLoadedContext,
    OnMessagesLoadedContext,
    OnRenderContextMergeContext,
    OnSerializeContext,
    OnSlotRenderedContext,
    OnTemplateCompiledContext,
    OnTemplateLoadedContext,
    OnTemplateResetContext,
    TemplateNamespaceContext,
    TemplateNamespaceContribution,
)
from citry.introspection import (
    AssetInfo,
    ComponentAssets,
    ComponentCatalog,
    ComponentExtensionInfo,
    ComponentInfo,
    ComponentIntrospectionError,
    ComponentSchemas,
    ExtensionVersion,
    FieldInfo,
    FrozenJsonObject,
    FrozenJsonValue,
    SchemaInfo,
)
from citry.library_component import (
    ComponentLibrary,
    LibraryComponent,
    LibraryComponentContextError,
    LibraryComponentInvocation,
    LibraryInstallation,
    LibraryInstallationStale,
    LibraryManifestChanged,
    LibraryNotInstalled,
)
from citry.lifecycle import CitryLifecycleInProgress
from citry.nodes import (
    ComponentNode,
    ElementAttrsNode,
    ElementKeyNode,
    ExprHtmlAttr,
    ExprNode,
    FillNode,
    ForNode,
    HtmlAttr,
    IfNode,
    Node,
    SlotNode,
    StaticHtmlAttr,
    TemplateHtmlAttr,
    TemplateNode,
)
from citry.settings import (
    CitrySettings,
    LintSettings,
    LintSeverity,
    SecurityCspMode,
    SecurityJavascriptMode,
    SecurityScriptIntegrityMode,
)
from citry.slots import (
    Slot,
    SlotContext,
    SlotData,
    SlotFunc,
    SlotInput,
    SlotResult,
)
from citry.util.routing import RouteHeaders, RouteRequest, RouteResponse, URLRoute
from citry_core.safe_eval import SecurityError

__all__ = [
    "AlreadyRegistered",
    "AssetInfo",
    "CacheConfig",
    "Citry",
    "CitryCache",
    "CitryContext",
    "CitryElement",
    "CitryLifecycleInProgress",
    "CitryRender",
    "CitrySettings",
    "CitryTemplate",
    "CommandArg",
    "CommandArgGroup",
    "CommandSubcommand",
    "Component",
    "ComponentAssets",
    "ComponentCatalog",
    "ComponentExtensionInfo",
    "ComponentInfo",
    "ComponentIntrospectionContext",
    "ComponentIntrospectionError",
    "ComponentLibrary",
    "ComponentLike",
    "ComponentNode",
    "ComponentSchemas",
    "Const",
    "CurrencyFormat",
    "DateFormat",
    "DateFormatFields",
    "DateInput",
    "DateParseResult",
    "DateSegments",
    "DateTimeFormat",
    "DateTimeInput",
    "DateTimeParseResult",
    "DateTimeSegments",
    "DependenciesConfig",
    "DepsPosition",
    "DepsStrategy",
    "ElementAttrsNode",
    "ElementKeyNode",
    "Events",
    "ExprHtmlAttr",
    "ExprNode",
    "Extension",
    "ExtensionCommand",
    "ExtensionConfig",
    "ExtensionManager",
    "ExtensionVersion",
    "FieldInfo",
    "FillNode",
    "ForNode",
    "FormatRegistry",
    "FrozenJsonObject",
    "FrozenJsonValue",
    "HtmlAttr",
    "I18n",
    "I18nError",
    "I18nFormatter",
    "I18nNotConfiguredError",
    "I18nParser",
    "I18nRuntimeUnavailableError",
    "I18nService",
    "IfNode",
    "InMemoryCache",
    "LibraryComponent",
    "LibraryComponentContextError",
    "LibraryComponentInvocation",
    "LibraryInstallation",
    "LibraryInstallationStale",
    "LibraryManifestChanged",
    "LibraryNotInstalled",
    "LintSettings",
    "LintSeverity",
    "ListFormat",
    "LocaleContext",
    "LocalizedText",
    "LspPosition",
    "LspRange",
    "Markup",
    "NestedClassDeclaration",
    "Node",
    "NotRegistered",
    "NumberFormat",
    "NumberInput",
    "NumberParseResult",
    "OnAttrsResolvedContext",
    "OnCitryClearedContext",
    "OnComponentClassCreatedContext",
    "OnComponentDataContext",
    "OnComponentInputContext",
    "OnComponentRegisteredContext",
    "OnComponentRenderedContext",
    "OnComponentUnregisteredContext",
    "OnCssLoadedContext",
    "OnExtensionCreatedContext",
    "OnFilesResetContext",
    "OnJsLoadedContext",
    "OnMessagesLoadedContext",
    "OnRenderContextMergeContext",
    "OnRenderGenerator",
    "OnSerializeContext",
    "OnSlotRenderedContext",
    "OnTemplateCompiledContext",
    "OnTemplateLoadedContext",
    "OnTemplateResetContext",
    "PercentFormat",
    "PercentInput",
    "PercentParseResult",
    "Placeholder",
    "PythonComponentAssetDiscovery",
    "PythonComponentAssetFile",
    "PythonComponentAssetFormatResult",
    "PythonComponentAssetKind",
    "PythonComponentAssetNotice",
    "PythonComponentAssetPlan",
    "PythonComponentAssetRegion",
    "PythonComponentAssetRequest",
    "PythonTemplateDiscovery",
    "PythonTemplateFormatError",
    "PythonTemplateFormatResult",
    "PythonTemplateNotice",
    "PythonTemplateRegion",
    "PythonTemplateSourceMap",
    "RelativeTimeFormat",
    "RenderFrame",
    "RenderReplacement",
    "RouteHeaders",
    "RouteRequest",
    "RouteResponse",
    "SchemaInfo",
    "SecurityCspMode",
    "SecurityError",
    "SecurityJavascriptMode",
    "SecurityScriptIntegrityMode",
    "SerializedRender",
    "SerializedScriptSecurity",
    "SerializedSecurity",
    "Slot",
    "SlotContext",
    "SlotData",
    "SlotFunc",
    "SlotInput",
    "SlotNode",
    "SlotResult",
    "StaticHtmlAttr",
    "TemplateAnalysis",
    "TemplateHtmlAttr",
    "TemplateLintConsumer",
    "TemplateLintFinding",
    "TemplateLintInfo",
    "TemplateNamespaceContext",
    "TemplateNamespaceContribution",
    "TemplateNode",
    "TemplateVariableInfo",
    "TimeFormat",
    "TimeInput",
    "TimeParseResult",
    "TimeSegments",
    "URLRoute",
    "UnitFormat",
    "citry",
    "const_value",
    "discover_python_component_assets",
    "discover_python_templates",
    "finish_python_component_assets",
    "format_attrs",
    "format_python_component_assets",
    "format_python_templates",
    "is_const",
    "lint_unknown_template_variables",
    "merge_attrs",
    "normalize_class",
    "normalize_style",
    "parse_string_style",
    "prepare_python_component_assets",
]
