"""
Valid values of enumerated HTML attributes. Generated; do not edit.

Run python scripts/generate_html_attribute_values.py to refresh it.
Source: https://html.spec.whatwg.org/multipage/indices.html
WHATWG HTML Standard, Last Updated 29 September 2026; retrieved 2026-10-01.
"""

# ruff: noqa: E501, Q000
# fmt: off

from __future__ import annotations

from typing import Final

# HTML element names, so a custom element or a component tag is never checked.
HTML_ELEMENTS: Final[frozenset[str]] = frozenset(('a', 'abbr', 'address', 'area', 'article', 'aside', 'audio', 'b', 'base', 'bdi', 'bdo', 'blockquote', 'body',
 'br', 'button', 'canvas', 'caption', 'cite', 'code', 'col', 'colgroup', 'data', 'datalist', 'dd', 'del',
 'details', 'dfn', 'dialog', 'div', 'dl', 'dt', 'em', 'embed', 'fieldset', 'figcaption', 'figure', 'footer',
 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'header', 'hgroup', 'hr', 'html', 'i', 'iframe', 'img',
 'input', 'ins', 'kbd', 'label', 'legend', 'li', 'link', 'main', 'map', 'mark', 'menu', 'meta', 'meter',
 'nav', 'noscript', 'object', 'ol', 'optgroup', 'option', 'output', 'p', 'picture', 'pre', 'progress', 'q',
 'rp', 'rt', 'ruby', 's', 'samp', 'script', 'search', 'section', 'select', 'selectedcontent', 'slot', 'small',
 'source', 'span', 'strong', 'style', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'template', 'textarea',
 'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'track', 'u', 'ul', 'var', 'video', 'wbr'))

# attribute -> element ("*" for every HTML element) -> allowed keywords.
# "" means the empty string, or the attribute with no value, is allowed.
ENUMERATED_VALUES: Final[dict[str, dict[str, tuple[str, ...]]]] = {'accept-charset': {'form': ('UTF-8',)},
 'autocapitalize': {'*': ('on', 'off', 'none', 'sentences', 'words', 'characters')},
 'autocomplete': {'form': ('on', 'off')},
 'autocorrect': {'*': ('on', 'off', '')},
 'charset': {'meta': ('utf-8',)},
 'closedby': {'dialog': ('any', 'closerequest', 'none')},
 'colorspace': {'input': ('limited-srgb', 'display-p3')},
 'contenteditable': {'*': ('true', 'false', 'plaintext-only', '')},
 'crossorigin': {'audio': ('anonymous', 'use-credentials', ''),
                 'img': ('anonymous', 'use-credentials', ''),
                 'link': ('anonymous', 'use-credentials', ''),
                 'script': ('anonymous', 'use-credentials', ''),
                 'video': ('anonymous', 'use-credentials', '')},
 'decoding': {'img': ('sync', 'async', 'auto')},
 'dir': {'*': ('ltr', 'rtl', 'auto'), 'bdo': ('ltr', 'rtl')},
 'draggable': {'*': ('true', 'false')},
 'enctype': {'form': ('application/x-www-form-urlencoded', 'multipart/form-data', 'text/plain')},
 'enterkeyhint': {'*': ('enter', 'done', 'go', 'next', 'previous', 'search', 'send')},
 'fetchpriority': {'img': ('auto', 'high', 'low'),
                   'link': ('auto', 'high', 'low'),
                   'script': ('auto', 'high', 'low')},
 'formenctype': {'button': ('application/x-www-form-urlencoded', 'multipart/form-data', 'text/plain'),
                 'input': ('application/x-www-form-urlencoded', 'multipart/form-data', 'text/plain')},
 'formmethod': {'button': ('get', 'post', 'dialog'), 'input': ('get', 'post', 'dialog')},
 'hidden': {'*': ('until-found', 'hidden', '')},
 'http-equiv': {'meta': ('content-type',
                         'default-style',
                         'refresh',
                         'x-ua-compatible',
                         'content-security-policy')},
 'inputmode': {'*': ('none', 'text', 'tel', 'email', 'url', 'numeric', 'decimal', 'search')},
 'kind': {'track': ('subtitles', 'captions', 'descriptions', 'chapters', 'metadata')},
 'loading': {'audio': ('lazy', 'eager'),
             'iframe': ('lazy', 'eager'),
             'img': ('lazy', 'eager'),
             'video': ('lazy', 'eager')},
 'method': {'form': ('get', 'post', 'dialog')},
 'popover': {'*': ('auto', 'manual', 'hint', '')},
 'popovertargetaction': {'button': ('toggle', 'show', 'hide'), 'input': ('toggle', 'show', 'hide')},
 'preload': {'audio': ('none', 'metadata', 'auto', ''), 'video': ('none', 'metadata', 'auto', '')},
 'referrerpolicy': {'a': ('',
                          'no-referrer',
                          'no-referrer-when-downgrade',
                          'same-origin',
                          'origin',
                          'strict-origin',
                          'origin-when-cross-origin',
                          'strict-origin-when-cross-origin',
                          'unsafe-url'),
                    'area': ('',
                             'no-referrer',
                             'no-referrer-when-downgrade',
                             'same-origin',
                             'origin',
                             'strict-origin',
                             'origin-when-cross-origin',
                             'strict-origin-when-cross-origin',
                             'unsafe-url'),
                    'iframe': ('',
                               'no-referrer',
                               'no-referrer-when-downgrade',
                               'same-origin',
                               'origin',
                               'strict-origin',
                               'origin-when-cross-origin',
                               'strict-origin-when-cross-origin',
                               'unsafe-url'),
                    'img': ('',
                            'no-referrer',
                            'no-referrer-when-downgrade',
                            'same-origin',
                            'origin',
                            'strict-origin',
                            'origin-when-cross-origin',
                            'strict-origin-when-cross-origin',
                            'unsafe-url'),
                    'link': ('',
                             'no-referrer',
                             'no-referrer-when-downgrade',
                             'same-origin',
                             'origin',
                             'strict-origin',
                             'origin-when-cross-origin',
                             'strict-origin-when-cross-origin',
                             'unsafe-url'),
                    'script': ('',
                               'no-referrer',
                               'no-referrer-when-downgrade',
                               'same-origin',
                               'origin',
                               'strict-origin',
                               'origin-when-cross-origin',
                               'strict-origin-when-cross-origin',
                               'unsafe-url')},
 'scope': {'th': ('row', 'col', 'rowgroup', 'colgroup')},
 'shadowrootmode': {'template': ('open', 'closed')},
 'shadowrootslotassignment': {'template': ('named', 'manual')},
 'shape': {'area': ('circle', 'default', 'poly', 'rect')},
 'spellcheck': {'*': ('true', 'false', '')},
 'translate': {'*': ('yes', 'no', '')},
 'type': {'button': ('submit', 'reset', 'button'),
          'input': ('button',
                    'checkbox',
                    'color',
                    'date',
                    'datetime-local',
                    'email',
                    'file',
                    'hidden',
                    'image',
                    'month',
                    'number',
                    'password',
                    'radio',
                    'range',
                    'reset',
                    'search',
                    'submit',
                    'tel',
                    'text',
                    'time',
                    'url',
                    'week'),
          'li': ('1', 'a', 'A', 'i', 'I', 'none', 'disc', 'circle', 'square'),
          'ol': ('1', 'a', 'A', 'i', 'I'),
          'ul': ('none', 'disc', 'circle', 'square')},
 'wrap': {'textarea': ('soft', 'hard')},
 'writingsuggestions': {'*': ('true', 'false', '')}}

# (element, attribute) -> the keywords that compare with letter case.
CASE_SENSITIVE_KEYWORDS: Final[dict[tuple[str, str], tuple[str, ...]]] = {('li', 'type'): ('1', 'a', 'A', 'i', 'I'), ('ol', 'type'): ('1', 'a', 'A', 'i', 'I')}

# Keywords for an attribute that otherwise takes any name not starting with "_".
NAVIGABLE_TARGET_KEYWORDS: Final[tuple[str, ...]] = ('_blank', '_self', '_parent', '_top')
NAVIGABLE_TARGET_ATTRIBUTES: Final[dict[str, tuple[str, ...]]] = {'formtarget': ('button', 'input'), 'target': ('a', 'area', 'base', 'form')}

# Elements whose `name` may not start with "_" at all.
FRAME_NAME_ELEMENTS: Final[tuple[str, ...]] = ('iframe', 'object')
