[package]
name = "citry_template_formatter"
description = "Format authored Citry templates"
version = "0.0.0"
edition = "2024"
rust-version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
publish = false

[dependencies]
citry_template_parser = { path = "../citry_template_parser" }
ruff_formatter = { workspace = true }
ruff_python_ast = { workspace = true }
ruff_python_formatter = { workspace = true }
ruff_python_parser = { workspace = true }
ruff_python_trivia = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
