"""Citry language-server package and protocol declarations."""

from citry_lsp.protocol import (
    CATALOG_SCHEMA_VERSION,
    EMBEDDED_FORMATTING_VERSION,
    FORMAT_COMPONENT_ASSETS_METHOD,
    FORMAT_EMBEDDED_METHOD,
    FORMAT_TEMPLATES_METHOD,
    PROTOCOL_VERSION,
    SERVER_VERSION,
    SUPPORTED_CITRY_SERIES,
)

__all__ = [
    "CATALOG_SCHEMA_VERSION",
    "EMBEDDED_FORMATTING_VERSION",
    "FORMAT_COMPONENT_ASSETS_METHOD",
    "FORMAT_EMBEDDED_METHOD",
    "FORMAT_TEMPLATES_METHOD",
    "PROTOCOL_VERSION",
    "SERVER_VERSION",
    "SUPPORTED_CITRY_SERIES",
]
