"""Generate the audited Citry UI Icon geometry catalog from Lucide SVGs."""

from __future__ import annotations

import hashlib
import html
import re
import urllib.request
from pathlib import Path
from xml.etree import ElementTree as ET

LUCIDE_VERSION = "1.30.0"
OUTPUT = Path(__file__).resolve().parents[1] / "_catalog.py"

ICON_SOURCES = {
    "arrow-down": "arrow-down",
    "arrow-left": "arrow-left",
    "arrow-right": "arrow-right",
    "arrow-up": "arrow-up",
    "calendar": "calendar",
    "check": "check",
    "chevron-down": "chevron-down",
    "chevron-left": "chevron-left",
    "chevron-right": "chevron-right",
    "chevron-up": "chevron-up",
    "circle-check": "circle-check",
    "circle-help": "circle-question-mark",
    "circle-info": "info",
    "circle-x": "circle-x",
    "clock": "clock",
    "copy": "copy",
    "download": "download",
    "edit": "pencil",
    "external-link": "external-link",
    "eye": "eye",
    "eye-off": "eye-off",
    "file": "file",
    "folder": "folder",
    "heart": "heart",
    "home": "house",
    "leaf": "leaf",
    "link": "link",
    "lock": "lock",
    "mail": "mail",
    "menu": "menu",
    "minus": "minus",
    "more-horizontal": "ellipsis",
    "more-vertical": "ellipsis-vertical",
    "plus": "plus",
    "refresh-cw": "refresh-cw",
    "search": "search",
    "settings": "settings",
    "star": "star",
    "trash": "trash",
    "triangle-alert": "triangle-alert",
    "unlock": "lock-open",
    "upload": "upload",
    "user": "user",
    "x": "x",
}

ROOT_ATTRIBUTES = {
    "width": "24",
    "height": "24",
    "viewBox": "0 0 24 24",
    "fill": "none",
    "stroke": "currentColor",
    "stroke-width": "2",
    "stroke-linecap": "round",
    "stroke-linejoin": "round",
}
CHILD_ATTRIBUTES = {
    "path": frozenset({"d"}),
    "circle": frozenset({"cx", "cy", "r"}),
    "rect": frozenset({"x", "y", "width", "height", "rx", "ry"}),
}
FORBIDDEN_VALUE = re.compile(r"(?:javascript:|data:|https?:|url\s*\(|<|>)", re.IGNORECASE)


def _local_name(name: str) -> str:
    return name.rsplit("}", 1)[-1]


def _fetch(name: str) -> bytes:
    url = f"https://raw.githubusercontent.com/lucide-icons/lucide/{LUCIDE_VERSION}/icons/{name}.svg"
    request = urllib.request.Request(  # noqa: S310 - fixed HTTPS origin
        url,
        headers={"User-Agent": "citry-ui-vendor/1"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:  # noqa: S310 - fixed HTTPS origin
        return response.read()


def _geometry(public_name: str, source_name: str) -> tuple[str, str]:
    source = _fetch(source_name)
    root = ET.fromstring(source)  # noqa: S314 - fixed trusted upstream plus allowlist below
    if _local_name(root.tag) != "svg" or root.attrib != ROOT_ATTRIBUTES:
        msg = f"Unexpected Lucide root contract for {public_name!r}: {root.attrib!r}"
        raise ValueError(msg)
    if root.text and root.text.strip():
        raise ValueError(f"Unexpected Lucide root text for {public_name!r}.")

    rendered: list[str] = []
    for child in root:
        tag = _local_name(child.tag)
        allowed = CHILD_ATTRIBUTES.get(tag)
        if allowed is None or not set(child.attrib) <= allowed:
            msg = f"Unexpected Lucide geometry for {public_name!r}: <{tag}> {child.attrib!r}"
            raise ValueError(msg)
        if list(child) or (child.text and child.text.strip()):
            raise ValueError(f"Nested or textual Lucide geometry for {public_name!r} is not allowed.")
        if any(FORBIDDEN_VALUE.search(value) for value in child.attrib.values()):
            raise ValueError(f"Executable or external Lucide geometry for {public_name!r} is not allowed.")
        attrs = " ".join(f'{key}="{html.escape(value, quote=True)}"' for key, value in sorted(child.attrib.items()))
        rendered.append(f"<{tag} {attrs}></{tag}>")
        if child.tail and child.tail.strip():
            raise ValueError(f"Unexpected Lucide geometry tail for {public_name!r}.")

    digest = hashlib.sha256(source).hexdigest()
    return "".join(rendered), digest


def main() -> None:
    glyphs: dict[str, str] = {}
    digests: dict[str, str] = {}
    for public_name, source_name in ICON_SOURCES.items():
        glyphs[public_name], digests[public_name] = _geometry(public_name, source_name)

    lines = [
        '"""Generated, audited Lucide geometry for Citry UI Icon."""',
        "",
        "# Generated by tools/vendor_lucide.py. Do not edit by hand.",
        "# ruff: noqa: E501",
        "",
        "from types import MappingProxyType",
        "from typing import Final",
        "",
        f'LUCIDE_VERSION: Final = "{LUCIDE_VERSION}"',
        "",
        "ICON_GLYPHS: Final = MappingProxyType({",
    ]
    lines.extend(f"    {name!r}: {glyphs[name]!r}," for name in sorted(glyphs))
    lines.extend(["})", "", "ICON_SOURCES: Final = MappingProxyType({"])
    lines.extend(f"    {name!r}: {ICON_SOURCES[name]!r}," for name in sorted(ICON_SOURCES))
    lines.extend(["})", "", "ICON_SOURCE_SHA256: Final = MappingProxyType({"])
    lines.extend(f"    {name!r}: {digests[name]!r}," for name in sorted(digests))
    lines.extend(["})", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
