"""Executable construction and validation for the client ownership graph."""

# This directory is the canonical source. ``scripts/sync_protocol_python.py``
# copies it byte for byte into ``citry._protocol.client_graph`` for release.

from .canonical import (
    COMMENT_PREFIX,
    MAX_SAFE_INTEGER,
    PROTOCOL,
    REVISION_ALIAS_LENGTH,
    canonical_json,
    format_ownership_comment,
    inert_script_json,
    parse_ownership_comment,
    revision_alias,
    revision_for,
)
from .issues import ProtocolValueError, ValidationIssue, copy_json, validate_strict_json
from .manifests import (
    assemble_manifest,
    assert_valid_manifest,
    build_manifest,
    serialize_manifest,
    validate_manifest,
    validate_revision,
)
from .records import (
    assemble_graph,
    build_client_binding,
    build_component_class,
    build_component_instance,
    build_dom_event_payload,
    build_execution_constraint,
    build_expression_payload,
    build_fill,
    build_graph,
    build_nested_component,
    build_poll_payload,
    build_slot_region,
    build_source_location,
    validate_client_binding,
    validate_client_binding_payload,
    validate_component_class,
    validate_component_instance,
    validate_execution_constraint,
    validate_fill,
    validate_graph,
    validate_nested_component,
    validate_slot_region,
    validate_source_location,
)
from .relationships import validate_relationships

__all__ = [
    "COMMENT_PREFIX",
    "MAX_SAFE_INTEGER",
    "PROTOCOL",
    "REVISION_ALIAS_LENGTH",
    "ProtocolValueError",
    "ValidationIssue",
    "assemble_graph",
    "assemble_manifest",
    "assert_valid_manifest",
    "build_client_binding",
    "build_component_class",
    "build_component_instance",
    "build_dom_event_payload",
    "build_execution_constraint",
    "build_expression_payload",
    "build_fill",
    "build_graph",
    "build_manifest",
    "build_nested_component",
    "build_poll_payload",
    "build_slot_region",
    "build_source_location",
    "canonical_json",
    "copy_json",
    "format_ownership_comment",
    "inert_script_json",
    "parse_ownership_comment",
    "revision_alias",
    "revision_for",
    "serialize_manifest",
    "validate_client_binding",
    "validate_client_binding_payload",
    "validate_component_class",
    "validate_component_instance",
    "validate_execution_constraint",
    "validate_fill",
    "validate_graph",
    "validate_manifest",
    "validate_nested_component",
    "validate_relationships",
    "validate_revision",
    "validate_slot_region",
    "validate_source_location",
    "validate_strict_json",
]
