#!/usr/bin/env bash
#
# Vendor the django-components reference snapshots used during the citry
# migration. These snapshots are gitignored (they are a large third-party
# copy); this script is the tracked, reproducible record of WHAT was vendored
# and from WHERE.
#
# Two snapshots are produced under packages/py/citry/ :
#   _djc_reference/             <- upstream src/django_components/ (engine source)
#   _djc_reference_docs_site/   <- upstream docs_site/ (the docs-site port basis)
#
# The engine snapshot is cited by file:line across docs/design/*.md, so its
# contents must be reproducible. Re-running this script against the pinned
# commit reproduces the exact snapshot the design docs were written against.
# The completed test migration records pinned upstream test links directly in
# docs/design/migration_djc_tests.md; it no longer keeps a local test copy.
#
# Usage:
#   scripts/vendor_djc_reference.sh [path-to-django-components-checkout]
#
# Default checkout path is $DJC_CHECKOUT or /Users/mac/repos/django-components.

set -euo pipefail

# --- Provenance -------------------------------------------------------------
# Upstream: https://github.com/django-components/django-components
# Branch at vendor time: jo-docs-mkdocs-migrate (PR #1664, the docs-site work)
# Pinned commit:
DJC_COMMIT="5d4d4f5d13dd06c80ba389f30fc63fdbb71cda75"  # 2026-06-20
# When PR #1664 merges to master, re-pin this to the merge commit on master.

CHECKOUT="${1:-${DJC_CHECKOUT:-/Users/mac/repos/django-components}}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DST="$REPO_ROOT/packages/py/citry"

if [[ ! -d "$CHECKOUT/.git" ]]; then
  echo "error: '$CHECKOUT' is not a git checkout. Clone django-components there," >&2
  echo "       or pass the path / set DJC_CHECKOUT." >&2
  exit 1
fi

have="$(git -C "$CHECKOUT" rev-parse HEAD)"
if [[ "$have" != "$DJC_COMMIT" ]]; then
  echo "warning: checkout is at $have, expected pinned $DJC_COMMIT." >&2
  echo "         Run: git -C '$CHECKOUT' fetch && git -C '$CHECKOUT' checkout $DJC_COMMIT" >&2
  echo "         Continuing anyway (Ctrl-C to abort)..." >&2
fi

# Excludes: generated output and the 1 GB versions/ history are not part of the
# reference (they are regenerated by the citry builder, not ported from).
COMMON_EXCLUDES=(--exclude='__pycache__/' --exclude='*.pyc'
                 --exclude='.pytest_cache/' --exclude='.ruff_cache/'
                 --exclude='.mypy_cache/')

echo "Vendoring engine source -> _djc_reference/"
rsync -a --delete "${COMMON_EXCLUDES[@]}" \
  "$CHECKOUT/src/django_components/" "$DST/_djc_reference/"

echo "Vendoring docs site     -> _djc_reference_docs_site/"
# versions/ is 1 GB of built HTML history; staticfiles/ is collectstatic output;
# .cache/ is the generated OpenGraph social-card image cache. All regenerated,
# none are part of the source to port from.
rsync -a --delete "${COMMON_EXCLUDES[@]}" \
  --exclude='versions/' --exclude='staticfiles/' --exclude='.cache/' \
  "$CHECKOUT/docs_site/" "$DST/_djc_reference_docs_site/"

echo "Done. Engine: $(find "$DST/_djc_reference" -name '*.py' | wc -l | tr -d ' ') py files."
echo "      Docs:   $(du -sh "$DST/_djc_reference_docs_site" | cut -f1) (versions/ excluded)."
