[package]
name = "citry_html_transform"
description = "Transform HTML in a single pass, applying changes needed by Citry"
version = "1.0.3"
edition = "2021"
rust-version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }

[dependencies]
quick-xml = { workspace = true }
