# ruff: noqa: T201 - a maintenance script that prints its progress to stdout
"""
Refresh the docs-site people data (``docs_site/data/people.yml``), the avatar
grids the ``<c-people />`` component renders.

It counts merged pull requests per author across **both** the citry and the
django-components repositories and merges the totals: citry is the continuation
of django-components, so a contributor to either project is credited here. The
maintainers and special thanks are featured separately; everyone
else is a contributor with their merged-PR count.

Ported from django-components' ``scripts/people.py`` (PR #1664), which is in turn
inspired by @tiangolo's FastAPI People script. Pure standard library, like
``scripts/supported_versions.py``, so it needs no install step; it reads
``GITHUB_TOKEN`` (any token that can read public repositories) from the
environment for the GitHub GraphQL API.

Run it directly to refresh the file:

    GITHUB_TOKEN=... python docs_site/scripts/people.py
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter
from pathlib import Path
from urllib.error import URLError
from urllib.request import Request, urlopen

# Merged PRs in these repositories count toward the grid; the counts are summed
# per author across all of them.
REPOS = [
    ("citry-dev", "citry"),
    ("django-components", "django-components"),
]

# Shown in featured groups rather than counted among contributors. Edit these
# lists to change who is featured.
MAINTAINERS = ["JuroOravec"]
SPECIAL_THANKS = ["EmilStenstrom"]

# Automated accounts left out of the contributor list.
BOT_LOGINS = {
    "dependabot",
    "dependabot[bot]",
    "github-actions",
    "github-actions[bot]",
    "pre-commit-ci",
    "pre-commit-ci[bot]",
    "copilot-swe-agent",
    "copilot-swe-agent[bot]",
}

DOCS_SITE_DIR = Path(__file__).resolve().parents[1]
PEOPLE_PATH = DOCS_SITE_DIR / "data" / "people.yml"

GRAPHQL_URL = "https://api.github.com/graphql"
_PRS_QUERY = """
query($owner: String!, $name: String!, $after: String) {
  repository(owner: $owner, name: $name) {
    pullRequests(first: 100, after: $after, states: [MERGED]) {
      pageInfo { hasNextPage endCursor }
      nodes { author { login avatarUrl url } }
    }
  }
}
"""

_HEADER = """\
# Community avatar-grid data, rendered by the <c-people group="..." /> component.
# Fields per person: login (GitHub handle), avatarUrl, url, and, for
# contributors, count (merged pull requests).
#
# Generated by docs_site/scripts/people.py, which counts merged PRs across the
# citry and django-components repositories and merges the totals (citry
# continues django-components, so a contributor to either is credited here).
# Re-run the script, or the "Docs people" workflow, to refresh. Do not edit by
# hand.
"""


def _graphql(token: str, variables: dict[str, str | None]) -> dict:
    """Run the merged-PR query for one page and return the pullRequests object."""
    body = json.dumps({"query": _PRS_QUERY, "variables": variables}).encode("utf-8")
    request = Request(  # noqa: S310 - fixed https GraphQL endpoint
        GRAPHQL_URL,
        data=body,
        headers={
            "Authorization": f"bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "citry-people-script",
        },
    )
    with urlopen(request, timeout=30) as response:  # noqa: S310
        data = json.load(response)
    if data.get("errors"):
        msg = json.dumps(data["errors"])
        raise RuntimeError(msg)
    return data["data"]["repository"]["pullRequests"]


def _merged_pr_authors(token: str, owner: str, name: str) -> list[dict[str, str]]:
    """Every merged PR author in owner/name, following pagination."""
    authors: list[dict[str, str]] = []
    after: str | None = None
    while True:
        prs = _graphql(token, {"owner": owner, "name": name, "after": after})
        authors.extend(node["author"] for node in prs["nodes"] if node["author"])
        if not prs["pageInfo"]["hasNextPage"]:
            return authors
        after = prs["pageInfo"]["endCursor"]


def collect_people(token: str) -> dict[str, list[dict]]:
    """Split merged-PR authors into featured and contributor groups."""
    counts: Counter[str] = Counter()
    profiles: dict[str, dict[str, str]] = {}
    for owner, name in REPOS:
        for author in _merged_pr_authors(token, owner, name):
            counts[author["login"]] += 1
            profiles[author["login"]] = author  # keep the most recent avatar/url

    maintainers = [
        {"login": login, "avatarUrl": profiles[login]["avatarUrl"], "url": profiles[login]["url"]}
        for login in MAINTAINERS
        if login in profiles
    ]
    special_thanks = [
        {"login": login, "avatarUrl": profiles[login]["avatarUrl"], "url": profiles[login]["url"]}
        for login in SPECIAL_THANKS
        if login in profiles
    ]

    skip = set(MAINTAINERS) | set(SPECIAL_THANKS) | BOT_LOGINS
    contributors = [
        {"login": login, "avatarUrl": profiles[login]["avatarUrl"], "url": profiles[login]["url"], "count": count}
        for login, count in counts.most_common()
        if login not in skip
    ]
    return {
        "maintainers": maintainers,
        "special_thanks": special_thanks,
        "contributors": contributors,
    }


def dump_people_yaml(people: dict[str, list[dict]]) -> str:
    """
    Emit the people data as YAML by hand (keeps the script standard-library-only).

    The values are GitHub logins and URLs, which are safe as plain YAML scalars,
    so the output matches the hand-seeded file's format and stays diff-friendly.
    """
    lines = [_HEADER.rstrip()]
    for group in ("maintainers", "special_thanks", "contributors"):
        entries = people[group]
        if not entries:
            lines.append(f"{group}: []")
            continue
        lines.append(f"{group}:")
        for person in entries:
            lines.append(f"- login: {person['login']}")
            lines.append(f"  avatarUrl: {person['avatarUrl']}")
            lines.append(f"  url: {person['url']}")
            if "count" in person:
                lines.append(f"  count: {person['count']}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Refresh docs_site/data/people.yml from merged PRs.")
    parser.add_argument("--output", type=Path, default=PEOPLE_PATH, help="where to write the people YAML")
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token:
        print("error: set GITHUB_TOKEN (a token that can read public repositories)", file=sys.stderr)
        return 2

    try:
        people = collect_people(token)
    except (URLError, RuntimeError, KeyError) as exc:
        print(f"error: could not fetch contributor data: {exc}", file=sys.stderr)
        return 2

    args.output.write_text(dump_people_yaml(people), encoding="utf-8")
    print(
        f"wrote {args.output}: {len(people['maintainers'])} maintainers, "
        f"{len(people['special_thanks'])} special thanks, "
        f"{len(people['contributors'])} contributors"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
