# ruff: noqa: T201 - a maintenance script that prints its progress to stdout
"""
Refresh the docs-site people data (``docs_site/data/people.yml``), the avatar
grids the ``<c-people />`` component renders.

It counts merged pull requests per author across the repositories declared in
``docs_site/people_sources.yml`` and merges the totals. Maintainers and special
thanks are featured separately; everyone else is a contributor with their
merged-PR count.

Ported from django-components' ``scripts/people.py`` (PR #1664), which is in turn
inspired by @tiangolo's FastAPI People script. It uses the docs environment's
PyYAML dependency and reads ``GITHUB_TOKEN`` (any token that can read public
repositories) from the environment for the GitHub GraphQL API.

Run it as a module from the repository root to refresh the file:

    GITHUB_TOKEN=... uv run --no-sync python -m docs_site.scripts.people
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path
from typing import TYPE_CHECKING, NamedTuple
from urllib.error import URLError
from urllib.request import Request, urlopen

import yaml
from yaml.constructor import ConstructorError

if TYPE_CHECKING:
    from yaml.nodes import MappingNode

DOCS_SITE_DIR = Path(__file__).resolve().parents[1]
PEOPLE_PATH = DOCS_SITE_DIR / "data" / "people.yml"
SOURCES_PATH = DOCS_SITE_DIR / "people_sources.yml"

GRAPHQL_URL = "https://api.github.com/graphql"
_PRS_QUERY = """
query($owner: String!, $name: String!, $after: String) {
  repository(owner: $owner, name: $name) {
    pullRequests(first: 100, after: $after, states: [MERGED]) {
      pageInfo { hasNextPage endCursor }
      nodes { author { login avatarUrl url } }
    }
  }
}
"""

_HEADER = """\
# Community avatar-grid data, rendered by the <c-people group="..." /> component.
# Fields per person: login (GitHub handle), avatarUrl, url, and, for
# contributors, count (merged pull requests).
#
# Generated by docs_site/scripts/people.py, which counts merged PRs across the
# repositories listed in docs_site/people_sources.yml and merges the totals.
# Re-run the script, or the "Docs people" workflow, to refresh. Do not edit by
# hand.
"""

_TOP_LEVEL_KEYS = frozenset({"repositories", "maintainers", "special_thanks", "ignored_logins"})
_REPOSITORY_KEYS = frozenset({"owner", "name"})
_OWNER_PATTERN = re.compile(r"(?!.*--)[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?\Z")
_REPOSITORY_PATTERN = re.compile(r"[A-Za-z0-9._-]{1,100}\Z")
_LOGIN_PATTERN = re.compile(r"(?!.*--)[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?(?:\[bot\])?\Z")


class Repository(NamedTuple):
    """A GitHub repository whose merged pull requests count toward People."""

    owner: str
    name: str


class PeopleSources(NamedTuple):
    """Validated, author-maintained inputs for the People generator."""

    repositories: tuple[Repository, ...]
    maintainers: tuple[str, ...]
    special_thanks: tuple[str, ...]
    ignored_logins: frozenset[str]


class PeopleSourcesError(ValueError):
    """A People source manifest cannot be used safely."""


class _UniqueKeyLoader(yaml.SafeLoader):
    """A safe YAML loader that rejects duplicate mapping keys."""


def _construct_unique_mapping(
    loader: _UniqueKeyLoader,
    node: MappingNode,
    *,
    deep: bool = False,
) -> dict[object, object]:
    mapping: dict[object, object] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        try:
            duplicate = key in mapping
        except TypeError as exc:
            raise ConstructorError(
                "while constructing a mapping",
                node.start_mark,
                "found an unhashable key",
                key_node.start_mark,
            ) from exc
        if duplicate:
            raise ConstructorError(
                "while constructing a mapping",
                node.start_mark,
                f"found duplicate key {key!r}",
                key_node.start_mark,
            )
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


_UniqueKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
    _construct_unique_mapping,
)


def _error(path: Path, field: str, message: str) -> PeopleSourcesError:
    return PeopleSourcesError(f"{path}: {field}: {message}")


def _mapping(
    value: object,
    *,
    path: Path,
    field: str,
    allowed_keys: frozenset[str],
) -> dict[str, object]:
    if not isinstance(value, dict):
        raise _error(path, field, "expected a mapping")
    unknown = [key for key in value if not isinstance(key, str) or key not in allowed_keys]
    if unknown:
        rendered = ", ".join(repr(key) for key in unknown)
        raise _error(path, field, f"unknown key: {rendered}")
    missing = [key for key in allowed_keys if key not in value]
    if missing:
        raise _error(path, field, f"missing required key: {', '.join(sorted(missing))}")
    return value


def _login_list(
    value: object,
    *,
    path: Path,
    field: str,
    require_entry: bool = False,
) -> tuple[str, ...]:
    if not isinstance(value, list):
        raise _error(path, field, "expected a list")
    if require_entry and not value:
        raise _error(path, field, "expected at least one login")

    result: list[str] = []
    seen: set[str] = set()
    for index, login in enumerate(value):
        item_field = f"{field}[{index}]"
        if not isinstance(login, str) or not _LOGIN_PATTERN.fullmatch(login):
            raise _error(path, item_field, "expected a valid GitHub login or GitHub App bot login")
        normalized = login.casefold()
        if normalized in seen:
            raise _error(path, item_field, f"duplicate login in {field}: {login!r}")
        seen.add(normalized)
        result.append(login)
    return tuple(result)


def _repositories(
    value: object,
    *,
    path: Path,
    site_repository: Repository | None,
) -> tuple[Repository, ...]:
    if not isinstance(value, list):
        raise _error(path, "repositories", "expected a list")
    if not value:
        raise _error(path, "repositories", "expected at least one repository")

    result: list[Repository] = []
    seen: set[tuple[str, str]] = set()
    for index, raw_repo in enumerate(value):
        field = f"repositories[{index}]"
        if raw_repo == "site":
            if site_repository is None:
                raise _error(path, field, "site repository settings are unavailable")
            owner, name = site_repository
        else:
            repo = _mapping(raw_repo, path=path, field=field, allowed_keys=_REPOSITORY_KEYS)
            owner = repo["owner"]
            name = repo["name"]
        if not isinstance(owner, str) or not _OWNER_PATTERN.fullmatch(owner):
            raise _error(path, f"{field}.owner", "expected a non-empty GitHub owner name")
        if not isinstance(name, str) or name in {".", ".."} or not _REPOSITORY_PATTERN.fullmatch(name):
            raise _error(path, f"{field}.name", "expected a non-empty GitHub repository name")
        normalized = (owner.casefold(), name.casefold())
        if normalized in seen:
            raise _error(path, field, f"duplicate repository: {owner}/{name}")
        seen.add(normalized)
        result.append(Repository(owner=owner, name=name))
    return tuple(result)


def load_people_sources(
    path: Path = SOURCES_PATH,
    *,
    site_repository: Repository | None = None,
) -> PeopleSources:
    """Load and strictly validate the author-maintained People inputs."""
    try:
        raw = yaml.load(path.read_text(encoding="utf-8"), Loader=_UniqueKeyLoader)  # noqa: S506 - safe loader subclass
    except (OSError, UnicodeError) as exc:
        raise _error(path, "<file>", str(exc)) from exc
    except yaml.YAMLError as exc:
        raise _error(path, "<yaml>", f"invalid YAML: {exc}") from exc

    root = _mapping(raw, path=path, field="<root>", allowed_keys=_TOP_LEVEL_KEYS)
    raw_repositories = root["repositories"]
    if isinstance(raw_repositories, list) and "site" in raw_repositories and site_repository is None:
        from docs_site._internal.settings import load_site_settings  # noqa: PLC0415

        configured = load_site_settings(path.with_name("settings.yml")).repository
        site_repository = Repository(configured.owner, configured.name)
    repositories = _repositories(raw_repositories, path=path, site_repository=site_repository)
    maintainers = _login_list(root["maintainers"], path=path, field="maintainers", require_entry=True)
    special_thanks = _login_list(root["special_thanks"], path=path, field="special_thanks")
    ignored_logins = _login_list(root["ignored_logins"], path=path, field="ignored_logins")

    maintainer_keys = {login.casefold() for login in maintainers}
    special_thanks_keys = {login.casefold() for login in special_thanks}
    overlap = maintainer_keys & special_thanks_keys
    if overlap:
        login = next(login for login in special_thanks if login.casefold() in overlap)
        raise _error(path, "special_thanks", f"login also appears in maintainers: {login!r}")

    featured_keys = maintainer_keys | special_thanks_keys
    ignored_overlap = featured_keys & {login.casefold() for login in ignored_logins}
    if ignored_overlap:
        login = next(login for login in ignored_logins if login.casefold() in ignored_overlap)
        raise _error(path, "ignored_logins", f"featured login cannot be ignored: {login!r}")

    return PeopleSources(
        repositories=repositories,
        maintainers=maintainers,
        special_thanks=special_thanks,
        ignored_logins=frozenset(ignored_logins),
    )


def _graphql(token: str, variables: dict[str, str | None]) -> dict:
    """Run the merged-PR query for one page and return the pullRequests object."""
    body = json.dumps({"query": _PRS_QUERY, "variables": variables}).encode("utf-8")
    request = Request(  # noqa: S310 - fixed https GraphQL endpoint
        GRAPHQL_URL,
        data=body,
        headers={
            "Authorization": f"bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "citry-people-script",
        },
    )
    with urlopen(request, timeout=30) as response:  # noqa: S310
        data = json.load(response)
    if data.get("errors"):
        msg = json.dumps(data["errors"])
        raise RuntimeError(msg)
    repository = data.get("data", {}).get("repository")
    if repository is None:
        owner = variables["owner"]
        name = variables["name"]
        raise RuntimeError(f"repository {owner}/{name} was not found or is not accessible")
    return repository["pullRequests"]


def _merged_pr_authors(token: str, owner: str, name: str) -> list[dict[str, str]]:
    """Every merged PR author in owner/name, following pagination."""
    authors: list[dict[str, str]] = []
    after: str | None = None
    while True:
        prs = _graphql(token, {"owner": owner, "name": name, "after": after})
        authors.extend(node["author"] for node in prs["nodes"] if node["author"])
        if not prs["pageInfo"]["hasNextPage"]:
            return authors
        after = prs["pageInfo"]["endCursor"]


def collect_people(token: str, sources: PeopleSources) -> dict[str, list[dict]]:
    """Split merged-PR authors into featured and contributor groups."""
    counts: Counter[str] = Counter()
    profiles: dict[str, dict[str, str]] = {}
    for repository in sources.repositories:
        for author in _merged_pr_authors(token, repository.owner, repository.name):
            login_key = author["login"].casefold()
            counts[login_key] += 1
            profiles[login_key] = author  # keep the most recent spelling/avatar/url

    maintainers = [
        {
            "login": profiles[login.casefold()]["login"],
            "avatarUrl": profiles[login.casefold()]["avatarUrl"],
            "url": profiles[login.casefold()]["url"],
        }
        for login in sources.maintainers
        if login.casefold() in profiles
    ]
    special_thanks = [
        {
            "login": profiles[login.casefold()]["login"],
            "avatarUrl": profiles[login.casefold()]["avatarUrl"],
            "url": profiles[login.casefold()]["url"],
        }
        for login in sources.special_thanks
        if login.casefold() in profiles
    ]

    skip = {login.casefold() for login in (*sources.maintainers, *sources.special_thanks, *sources.ignored_logins)}
    contributors = [
        {
            "login": profiles[login_key]["login"],
            "avatarUrl": profiles[login_key]["avatarUrl"],
            "url": profiles[login_key]["url"],
            "count": count,
        }
        for login_key, count in counts.most_common()
        if login_key not in skip
    ]
    return {
        "maintainers": maintainers,
        "special_thanks": special_thanks,
        "contributors": contributors,
    }


def _yaml_string(value: str) -> str:
    """Keep a readable plain scalar only when YAML loads it as the same string."""
    try:
        loaded = yaml.safe_load(f"value: {value}\n")
    except yaml.YAMLError:
        loaded = None
    if loaded == {"value": value}:
        return value
    return json.dumps(value, ensure_ascii=True)


def dump_people_yaml(people: dict[str, list[dict]]) -> str:
    """
    Emit the people data as stable, readable YAML.

    Plain strings stay diff-friendly. Strings with YAML syntax or implicit YAML
    types are JSON-quoted, which is also valid YAML.
    """
    lines = [_HEADER.rstrip()]
    for group in ("maintainers", "special_thanks", "contributors"):
        entries = people[group]
        if not entries:
            lines.append(f"{group}: []")
            continue
        lines.append(f"{group}:")
        for person in entries:
            lines.append(f"- login: {_yaml_string(person['login'])}")
            lines.append(f"  avatarUrl: {_yaml_string(person['avatarUrl'])}")
            lines.append(f"  url: {_yaml_string(person['url'])}")
            if "count" in person:
                lines.append(f"  count: {person['count']}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Refresh docs_site/data/people.yml from merged PRs.")
    parser.add_argument(
        "--sources",
        type=Path,
        default=SOURCES_PATH,
        help="author-maintained repositories and featured People configuration",
    )
    parser.add_argument("--output", type=Path, default=PEOPLE_PATH, help="where to write the people YAML")
    args = parser.parse_args()

    try:
        sources = load_people_sources(args.sources)
    except PeopleSourcesError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token:
        print("error: set GITHUB_TOKEN (a token that can read public repositories)", file=sys.stderr)
        return 2

    try:
        people = collect_people(token, sources)
    except (URLError, RuntimeError, KeyError) as exc:
        print(f"error: could not fetch contributor data: {exc}", file=sys.stderr)
        return 2

    try:
        args.output.write_text(dump_people_yaml(people), encoding="utf-8")
    except OSError as exc:
        print(f"error: could not write {args.output}: {exc}", file=sys.stderr)
        return 2
    print(
        f"wrote {args.output}: {len(people['maintainers'])} maintainers, "
        f"{len(people['special_thanks'])} special thanks, "
        f"{len(people['contributors'])} contributors"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
